# Generated by Django 4.2.13 on 2024-05-21 18:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_title', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_title', models.CharField(max_length=150, null=True)),
                ('location_name', models.CharField(max_length=100)),
                ('location_contact', models.CharField(max_length=15)),
                ('location_address_1', models.CharField(max_length=100)),
                ('location_address_2', models.CharField(max_length=100, null=True)),
                ('location_city', models.CharField(max_length=100)),
                ('location_state', models.CharField(max_length=2)),
                ('location_zip', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('production_title', models.CharField(max_length=150, null=True)),
                ('production_studio', models.CharField(max_length=150, null=True)),
                ('production_email', models.EmailField(max_length=254, null=True, verbose_name='email address')),
                ('purchase_order', models.CharField(max_length=10, null=True)),
                ('coordinator_name', models.CharField(max_length=150, null=True)),
                ('coordinator_email', models.EmailField(max_length=254, null=True, verbose_name='email address')),
                ('captain_name', models.CharField(max_length=150, null=True)),
                ('captain_email', models.EmailField(max_length=254, null=True, verbose_name='email address')),
                ('production_notes', models.TextField(max_length=2000, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_phone', models.CharField(max_length=15)),
                ('vendor_address_1', models.CharField(max_length=100)),
                ('vendor_address_2', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_city', models.CharField(max_length=100)),
                ('vendor_state', models.CharField(max_length=2)),
                ('vendor_zip', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('department_title', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('user_name', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('production_title', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=150)),
                ('job_title', models.CharField(max_length=150)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
