# Generated by Django 5.0.4 on 2024-05-16 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_title', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_title', models.CharField(max_length=150, null=True)),
                ('location_name', models.CharField(max_length=100)),
                ('location_contact', models.CharField(max_length=15)),
                ('location_address_1', models.CharField(max_length=100)),
                ('location_address_2', models.CharField(max_length=100, null=True)),
                ('location_city', models.CharField(max_length=100)),
                ('location_state', models.CharField(max_length=2)),
                ('location_zip', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('production_title', models.CharField(max_length=150, null=True)),
                ('production_studio', models.CharField(max_length=150, null=True)),
                ('production_email', models.EmailField(max_length=254, null=True, verbose_name='email address')),
                ('purchase_order', models.CharField(max_length=10, null=True)),
                ('coordinator_name', models.CharField(max_length=150, null=True)),
                ('coordinator_email', models.EmailField(max_length=254, null=True, verbose_name='email address')),
                ('captain_name', models.CharField(max_length=150, null=True)),
                ('captain_email', models.EmailField(max_length=254, null=True, verbose_name='email address')),
                ('production_notes', models.TextField(max_length=2000, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_phone', models.CharField(max_length=15)),
                ('vendor_address_1', models.CharField(max_length=100)),
                ('vendor_address_2', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_city', models.CharField(max_length=100)),
                ('vendor_state', models.CharField(max_length=2)),
                ('vendor_zip', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('department_title', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
        ),
    ]
