# Generated by Django 4.2.13 on 2024-05-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='productions',
            field=models.ManyToManyField(related_name='users', to='core.production'),
        ),
    ]
