# Generated by Django 5.0.4 on 2024-07-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newuser_productions'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_address_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
