# Generated by Django 5.0.4 on 2024-07-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_location_location_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='department',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='productions',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.production'),
        ),
    ]
