# Generated by Django 5.0.4 on 2024-10-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_newuser_department_alter_newuser_job_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='production_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
