# Generated by Django 5.0.4 on 2024-10-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_user_name_newuser_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
