# Generated by Django 5.0.4 on 2024-11-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_production_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='dot_admin_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='production',
            name='dot_admin_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
