# Generated by Django 5.0.4 on 2024-11-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_production_dot_admin_email_production_dot_admin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='first_shoot_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='last_shoot_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='production_accountant_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='production',
            name='production_accountant_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='production_accountant_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='production_address_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='production_address_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='production_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='production_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='production_state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='production_supervisor_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='production',
            name='production_supervisor_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='production_type',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='production_zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='total_shoot_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='unit_production_manager_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='production',
            name='unit_production_manager_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
