# Generated by Django 5.0.4 on 2024-11-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_production_first_shoot_day_production_last_shoot_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='shoot_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='shoot_day',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
