# Generated by Django 5.0.4 on 2024-11-30 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_location_shoot_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_phone', models.CharField(max_length=15)),
                ('vendor_address_1', models.CharField(max_length=100)),
                ('vendor_address_2', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_city', models.CharField(max_length=100)),
                ('vendor_state', models.CharField(max_length=2)),
                ('vendor_zip', models.CharField(max_length=10)),
                ('po_number', models.CharField(max_length=10)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('po_start_date', models.DateField(blank=True, null=True)),
                ('po_end_date', models.DateField(blank=True, null=True)),
                ('po_duration', models.IntegerField(blank=True, null=True)),
                ('po_type', models.CharField(blank=True, choices=[('', 'Select a PO Type'), ('Rental', 'Rental'), ('Purchase', 'Purchase'), ('Service', 'Service'), ('Other', 'Other')], max_length=10, null=True)),
                ('po_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('po_taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('po_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('po_description', models.TextField(blank=True, max_length=2000, null=True)),
                ('is_budgeted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('production_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.production')),
            ],
        ),
    ]
