# Generated by Django 5.0.4 on 2024-11-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_purchaseorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorders',
            name='po_ammount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorders',
            name='po_grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
