# Generated by Django 5.0.4 on 2024-11-30 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_purchaseorderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorders',
            old_name='po_total',
            new_name='po_subtotal',
        ),
    ]
