# Generated by Django 5.0.4 on 2024-12-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_po_total_purchaseorders_po_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorders',
            name='vendor_contact',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
