# Generated by Django 4.2.13 on 2024-05-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadioScanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=255)),
                ('production', models.CharField(max_length=100)),
                ('assigned_employee', models.CharField(max_length=100, null=True)),
                ('assigned_department', models.CharField(max_length=100)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(max_length=1000)),
            ],
        ),
    ]
