# Generated by Django 4.2.13 on 2024-05-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_title', models.CharField(max_length=150, null=True)),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('driver_email', models.EmailField(max_length=254, null=True, verbose_name='email address')),
                ('occupation_code', models.CharField(max_length=4, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('last_4', models.CharField(max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_title', models.CharField(max_length=150, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('requester_name', models.CharField(max_length=100)),
                ('requester_phone', models.CharField(max_length=15)),
                ('requester_email', models.CharField(max_length=255)),
                ('requester_department', models.CharField(max_length=100)),
                ('run_date', models.DateField()),
                ('pickup_name', models.CharField(max_length=100)),
                ('pickup_phone', models.CharField(max_length=15)),
                ('pickup_address_1', models.CharField(max_length=100)),
                ('pickup_address_2', models.CharField(max_length=100, null=True)),
                ('pickup_city', models.CharField(max_length=100)),
                ('pickup_state', models.CharField(max_length=2)),
                ('pickup_zip', models.CharField(max_length=10)),
                ('dropoff_name', models.CharField(max_length=100)),
                ('dropoff_phone', models.CharField(max_length=15)),
                ('dropoff_address_1', models.CharField(max_length=100)),
                ('dropoff_address_2', models.CharField(max_length=100, null=True)),
                ('dropoff_city', models.CharField(max_length=100)),
                ('dropoff_state', models.CharField(max_length=2)),
                ('dropoff_zip', models.CharField(max_length=10)),
                ('purchase_order', models.CharField(max_length=20, null=True)),
                ('vendor_invoice', models.CharField(max_length=20, null=True)),
                ('run_status', models.CharField(max_length=20, null=True)),
                ('truck_size', models.CharField(max_length=50, null=True)),
                ('run_details', models.TextField(max_length=500)),
                ('assigned_driver', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_title', models.CharField(max_length=150, null=True)),
                ('vehicle_type', models.CharField(max_length=150, null=True)),
                ('vendor_name', models.CharField(max_length=100, null=True)),
                ('vendor_unit_number', models.CharField(max_length=10, null=True)),
                ('internal_unit_number', models.CharField(max_length=20, null=True)),
                ('purchase_order', models.CharField(max_length=10, null=True)),
                ('vehicle_notes', models.TextField(max_length=2000, null=True)),
                ('assigned_driver', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
