# Generated by Django 4.2.13 on 2024-05-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runrequest',
            name='need_by_this_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='ready_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runrequest',
            name='assigned_driver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='runrequest',
            name='dropoff_address_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='runrequest',
            name='dropoff_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='runrequest',
            name='pickup_address_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='runrequest',
            name='pickup_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='runrequest',
            name='purchase_order',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='runrequest',
            name='truck_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='runrequest',
            name='vendor_invoice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
