# Generated by Django 4.2.13 on 2024-05-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0004_driver_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runrequest',
            name='run_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
