# Generated by Django 5.0.4 on 2024-07-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0006_driver_driver_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='runrequest',
            name='driver_notes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='run_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_3_address_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_3_address_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_3_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_3_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_3_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_3_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_3_zip',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_4_address_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_4_address_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_4_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_4_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_4_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_4_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_4_zip',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_5_address_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_5_address_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_5_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_5_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_5_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_5_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_5_zip',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_6_address_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_6_address_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_6_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_6_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_6_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_6_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_6_zip',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='transportation_notes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='runrequest',
            name='dropoff_address_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='runrequest',
            name='dropoff_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='runrequest',
            name='dropoff_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='runrequest',
            name='dropoff_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='runrequest',
            name='dropoff_zip',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
