# Generated by Django 5.0.4 on 2024-07-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0007_runrequest_driver_notes_runrequest_run_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runrequest',
            name='run_details_2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='run_details_3',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='run_details_4',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='run_details_5',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='run_details_6',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
