# Generated by Django 5.0.4 on 2024-07-24 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_newuser_department_alter_newuser_job_title_and_more'),
        ('transportation', '0008_runrequest_run_details_2_runrequest_run_details_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='assigned_vehicle',
            field=models.ManyToManyField(blank=True, related_name='drivers', to='transportation.vehicle'),
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='assigned_driver',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='production_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.production'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='assigned_driver',
            field=models.ManyToManyField(blank=True, related_name='vehicles', to='transportation.driver'),
        ),
    ]
