# Generated by Django 5.0.4 on 2024-07-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0010_vehicle_assigned_department_vehicle_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_notes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
