# Generated by Django 5.0.4 on 2024-10-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0011_alter_vehicle_vehicle_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='runrequest',
            name='drop_off_details',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_2_address_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_2_address_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_2_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_2_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_2_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_2_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='runrequest',
            name='stop_2_zip',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
