# Generated by Django 5.0.4 on 2024-10-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0012_runrequest_drop_off_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runrequest',
            old_name='drop_off_details',
            new_name='dropoff_details',
        ),
    ]
