# Generated by Django 5.0.4 on 2024-10-23 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0013_rename_drop_off_details_runrequest_dropoff_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='local',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DriverTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_title', models.CharField(max_length=255)),
                ('work_date', models.DateField()),
                ('call_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wrap_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lunch_1_out', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lunch_1_in', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lunch_2_out', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lunch_2_in', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.driver')),
            ],
        ),
    ]
