# Generated by Django 5.0.4 on 2024-10-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0016_rename_vehicle_equipment_driverdailyrundown'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='vehicle_notes',
            new_name='equipment_notes',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='vehicle_type',
            new_name='equipment_type_1',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='internal_unit_number',
            new_name='fleet_number',
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_type_2',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
