# Generated by Django 5.0.4 on 2024-10-23 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_production_code'),
        ('transportation', '0017_rename_vehicle_notes_equipment_equipment_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=4, null=True)),
                ('make', models.CharField(max_length=150, null=True)),
                ('model', models.CharField(max_length=150, null=True)),
                ('vendor_name', models.CharField(max_length=100, null=True)),
                ('vendor_unit_number', models.CharField(max_length=10, null=True)),
                ('scene', models.CharField(max_length=20, null=True)),
                ('purchase_order', models.CharField(max_length=10, null=True)),
                ('picture_car_notes', models.TextField(blank=True, max_length=2000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('production_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_cars', to='core.production')),
            ],
        ),
    ]
