# Generated by Django 5.0.4 on 2024-10-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0019_alter_picturecars_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='production_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driverdailyrundown',
            name='driver_times',
            field=models.ManyToManyField(to='transportation.drivertimes'),
        ),
    ]
