# Generated by Django 5.0.4 on 2024-10-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0020_driver_production_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdailyrundown',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
