# Generated by Django 5.0.4 on 2024-10-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0021_driverdailyrundown_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdailyrundown',
            name='driver_times',
            field=models.ManyToManyField(blank=True, to='transportation.drivertimes'),
        ),
    ]
