# Generated by Django 5.0.4 on 2024-10-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0022_alter_driverdailyrundown_driver_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdailyrundown',
            name='instructions',
        ),
        migrations.AddField(
            model_name='drivertimes',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
