# Generated by Django 5.0.4 on 2024-10-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0023_remove_driverdailyrundown_instructions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='assigned_vehicle',
        ),
        migrations.AddField(
            model_name='driver',
            name='assigned_trailer',
            field=models.ManyToManyField(limit_choices_to={'vehicle_type': 'trailer'}, related_name='assigned_trailer', to='transportation.equipment'),
        ),
        migrations.AddField(
            model_name='driver',
            name='assigned_truck',
            field=models.ManyToManyField(limit_choices_to={'vehicle_type': 'truck'}, related_name='assigned_truck', to='transportation.equipment'),
        ),
    ]
