# Generated by Django 5.0.4 on 2024-10-24 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_production_code'),
        ('transportation', '0026_alter_equipment_equipment_type_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='supporting_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='core.department'),
        ),
    ]
