# Generated by Django 5.0.4 on 2024-10-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0027_driver_supporting_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runrequest',
            name='assigned_driver',
        ),
        migrations.AddField(
            model_name='runrequest',
            name='assigned_driver',
            field=models.ManyToManyField(blank=True, to='transportation.driver'),
        ),
    ]
