# Generated by Django 5.0.4 on 2024-11-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0028_remove_runrequest_assigned_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertimes',
            name='non_deducted_breakfast_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='drivertimes',
            name='non_deducted_meal_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='drivertimes',
            name='non_deducted_meal_out',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
