# Generated by Django 5.0.4 on 2024-11-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0029_drivertimes_non_deducted_breakfast_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertimes',
            name='meal_penalty_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivertimes',
            name='meal_penalty_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
