# Generated by Django 5.0.4 on 2024-11-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0033_drivertimecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='trailer_type',
            field=models.CharField(blank=True, choices=[('cast_single', 'Cast Single'), ('cast_2_room', 'Cast 2-Room'), ('cast_3_room', 'Cast 3-Room'), ('cast_5_room', 'Cast 5-Room'), ('office_trailer', 'Office Trailer'), ('wardrobe_trailer', 'Wardrobe Trailer'), ('makeup_trailer', 'Makeup Trailer'), ('grip_trailer', 'Grip Trailer'), ('set_lighting_trailer', 'Set Lighting Trailer'), ('equipment_trailer', 'Equipment Trailer'), ('honeywagon', 'Honeywagon'), ('flatbed', 'Flatbed')], max_length=150, null=True),
        ),
    ]
