# Generated by Django 5.0.4 on 2024-11-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0034_equipment_trailer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type_2',
            field=models.CharField(blank=True, choices=[('stakebed', 'Stakebed'), ('box_truck', 'Box Truck'), ('5_ton', '5-Ton'), ('10_ton', '10-Ton'), ('tractor', 'Tractor'), ('production_van', 'Production Van'), ('van', 'Van')], max_length=150, null=True),
        ),
    ]
