# Generated by Django 5.0.4 on 2024-11-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0035_alter_equipment_equipment_type_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='vendor_invoice',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
