# Generated by Django 5.0.4 on 2024-11-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0037_equipment_vendor_address_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='drivers_license_class',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='drivers_license_endorsements',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='drivers_license_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='drivers_license_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='drivers_license_restrictions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='drivers_license_state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='medical_card_expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
