# Generated by Django 5.0.4 on 2024-11-20 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0038_driver_driver_birthdate_driver_drivers_license_class_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='job_classification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='MyCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('my_crew_first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('my_crew_last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('my_crew_driver_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('my_crew_driver_birthdate', models.DateField(blank=True, null=True)),
                ('my_crew_driver_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('my_crew_occupation_code', models.CharField(blank=True, max_length=4, null=True)),
                ('my_crew_job_classification', models.CharField(blank=True, max_length=50, null=True)),
                ('my_crew_driver_hire_date', models.DateField(blank=True, null=True)),
                ('my_crew_production_status', models.CharField(blank=True, max_length=50, null=True)),
                ('my_crew_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('my_crew_grouping', models.IntegerField(blank=True, null=True)),
                ('my_crew_local', models.IntegerField(blank=True, null=True)),
                ('my_crew_last_4', models.CharField(blank=True, max_length=6, null=True)),
                ('my_crew_drivers_license_number', models.CharField(blank=True, max_length=20, null=True)),
                ('my_crew_drivers_license_expiration', models.DateField(blank=True, null=True)),
                ('my_crew_drivers_license_state', models.CharField(blank=True, max_length=2, null=True)),
                ('my_crew_drivers_license_class', models.CharField(blank=True, max_length=2, null=True)),
                ('my_crew_drivers_license_endorsements', models.CharField(blank=True, max_length=50, null=True)),
                ('my_crew_drivers_license_restrictions', models.CharField(blank=True, max_length=50, null=True)),
                ('my_crew_medical_card_expiration', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('my_crew_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
