# Generated by Django 5.0.4 on 2024-11-23 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_location_shoot_day'),
        ('transportation', '0041_remove_mycrew_my_crew_driver_hire_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycrew',
            name='favorite_drivers',
        ),
        migrations.CreateModel(
            name='ProductionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.driver')),
                ('my_crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.mycrew')),
                ('production_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.production')),
            ],
        ),
        migrations.AddField(
            model_name='mycrew',
            name='production_history',
            field=models.ManyToManyField(blank=True, to='transportation.productionhistory'),
        ),
    ]
