# Generated by Django 5.0.4 on 2024-11-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_location_shoot_day'),
        ('transportation', '0043_rename_production_history_mycrew_my_crew_production_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycrew',
            name='my_crew_production_history',
            field=models.ManyToManyField(blank=True, to='core.production'),
        ),
    ]
